Dev/simple token builder2
AgoraIO/Tools pull request #14
Opened 2019-07-12 04:15 UTC by linshibo

2019-07-12 06:50 UTC, bobhust928 requested changes

2019-07-12 06:50 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/src/SimpleTokenBuilder2.h
> +  if (uid != 0) {
what if uid == 0?

2019-07-12 06:50 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/sample/rtm_builder2.cpp
> +  std::string appID  = "970CA35de60c44645bbae8a215061b33";
Why do we expose appID? Seems dangerous

2019-07-12 06:50 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/sample/rtm_builder2.cpp
> +  std::string appID  = "970CA35de60c44645bbae8a215061b33";
should leave a MACRO here, i.e., 
#define APP_ID

std::string appID = APP_ID; // Please define your APP_ID here

2019-07-12 06:50 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/test/RtmTokenBuilder2_test.cpp
> +    appID = "970CA35de60c44645bbae8a215061b33";
No AppID should be expose in any demo or examples

2019-07-12 06:59 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/src/SimpleTokenBuilder2.h
> +                                  uint32_t expiredTs = 0);
'expiredTs' -> 'privilegeExpiredTs'

2019-07-12 06:59 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/src/SimpleTokenBuilder2.h
> +  static std::string buildTokenWithUid(const std::string& appId,
因为Token 自身的有效期，是很重要的，也是安全性的重要标记，虽然客户可能会被tokenExpiredTs 和privilege expired TS搞混，我觉得我们仍然需要开放这个 字段，允许客户设置，只是token的有效期默认是当前值 （24小时？）

2019-07-12 07:41 UTC, linshibo commented on DynamicKey/AgoraDynamicKey/cpp/src/SimpleTokenBuilder2.h
> +  if (uid != 0) {
uid==0 等价与  userAccount == ""

2019-07-12 08:16 UTC, linshibo commented on DynamicKey/AgoraDynamicKey/cpp/sample/rtm_builder2.cpp
> +  std::string appID  = "970CA35de60c44645bbae8a215061b33";
970CA35de60c44645bbae8a215061b33   这个是个假的appid

2019-07-14 15:00 UTC, bobhust928 requested changes

2019-07-14 15:00 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/sample/rtm_builder2.cpp
> +  std::string appID  = "970CA35de60c44645bbae8a215061b33";
建议用Macro 表示，至少从代码这里，用户可以清晰知道需要替换这个app id

2019-07-14 15:00 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/src/RtmTokenBuilder2.h
> +                                RtmUserRole Rtm_User,
Rtm_User -》 userRole

2019-07-14 15:00 UTC, bobhust928 commented on DynamicKey/AgoraDynamicKey/cpp/src/SimpleTokenBuilder2.h
> +  static std::string buildTokenWithUid(const std::string& appId,
Add descriptions for each parameters, especially:

privilegeExpireTs, is represented by the number of seconds elapsed since 1/1/1970. If, for example, you want to access the Agora Service within 10 minutes after the token is generated, set expireTimestamp as the current timestamp + 600 (seconds).

2019-07-15 06:44 UTC, linshibo commented on DynamicKey/AgoraDynamicKey/cpp/sample/rtm_builder2.cpp
> +  std::string appID  = "970CA35de60c44645bbae8a215061b33";
都在用变量了啊  ，变量和宏没啥区别吧

2019-07-15 07:36 UTC, bobhust928 approved these changes

2019-07-16 03:46 UTC, vissidarte approved these changes

2019-07-16 06:46 UTC, plutoless approved these changes

2019-07-16 06:46 UTC, merged